# Generated by Django 5.1.3 on 2024-12-08 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasPremium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cantidad_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_caducidad', models.DateTimeField()),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_premium', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
