# Generated by Django 4.2.4 on 2024-11-20 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_rename_credenciales_tecnico_credenciales_tecnico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_credencial', models.FileField(blank=True, null=True, upload_to='credenciales/')),
                ('verificado', models.BooleanField(default=False)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciales_tecnicos', to='User.tecnico')),
            ],
        ),
    ]
