# Generated by Django 4.2.4 on 2024-11-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnico',
            old_name='credenciales',
            new_name='credenciales_tecnico',
        ),
    ]
