# Generated by Django 5.1.3 on 2024-12-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_credenciales_tecnico_credenciales_tecnico'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='tecnico',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
    ]
