# Generated by Django 5.1.3 on 2024-12-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tecnico_access_token_tecnico_es_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='access_token',
            field=models.CharField(blank=True, help_text='Access token del técnico para Mercado Pago', max_length=255, null=True),
        ),
    ]
